### ISSUE TITLE
Contribution guideline

### ISSUE THREAD

**Issue by lablnet** [adityagirinv/quotesmaker#4]
Any guideline for contributors?

**Comment by adityagirinv** [comment]
I am new to github so I am myself  confused😂😂😂😂

**Comment by adityagirinv** [comment]
soon i will add a guideline!!!

**Comment by lablnet** [comment]
> I am new to github so I am myself confused

you can watch 1 hr guide by freecodecamp => https://www.youtube.com/watch?v=RGOj5yH7evk
